### ISSUE TITLE
Baidu CDN not loading

### ISSUE THREAD

**Issue by oovz** [sherpahu/LeetcodeAnswerHelper#2]
the jquery from baidu cdn is not loading at my home. switching to jquery's cdn works

network: Washington, DC, Verizon Fios

**Comment by sherpahu** [comment]
It seems that I can't reproduce the problem. I am using education network in Beijing and I can search answers without problem. What's more, when using a proxy, I can also get the results with Baidu. I am using the proxy from HK, Singapore and  Japan. It is a pity that I don't have an American proxy. I am not sure whether it is the fault of your network.
And I am quite busy right now and I will try to refactoring my code in January after my final exam. Then I will try my best to fix your problem. Sorry about this!
My Wechat id is sherpahugongzhen. You can add my wechat if you are using it.

**Comment by oovz** [comment]
I guess it's HTTPS Everywhere that blocks jquery.min.js from loading since Baidu doesn't support HTTPS protocol, if I remember it correctly. I've switched to Jquery's and it works.
As a side note, I remember there are tons of CDN that support HTTPS protocol in mainland China and I'd suggest switching to one of them, if applicable.

**Comment by sherpahu** [comment]
OK, I get a new one now. Thank you!
